# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUitest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uitest(self):
    self.driver.get("https://karol-ununitable-degenerately.ngrok-free.dev/Shirel_Miryam_Project/index.jsp")
    self.driver.set_window_size(790, 816)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Hello DevOps")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(2000)
    assert self.driver.title == "DevOps Final Project"
  
